<a href="https://colab.research.google.com/github/marescost4/a/blob/main/Aula1certo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bioestatística

- David Souza 16965966
- Mariane Santana 16890981
- Fillipy Leal 17097358

# Tipos de variáveis

## Discreta

Número de bacterias numa suspensão (50.000 bactérias em 1 ml de água destilada)

## Continua

Comprimento da parte aérea de sementes germinadas em cm (0.1, 0.5, ..., 1)

## Ordinal

Grau de escolaridade (básico, médio, superior)

## Nominal

Disciplinas da área de biológicas (Bioquímica, Zoologia, Histologia, Anatomia, Ecologia)

In [1]:
import pandas as pd

df = pd.read_excel('dados.xlsx')

In [4]:
df

,Quantos dias por semana você estuda Biologia?,Quantas horas você dedica aos estudos de Biologia em uma semana?,Quantas espécies de plantas você consegue identificar corretamente em uma atividade prática?,"Qual o tamanho da folha analisada, em milímetros?",Qual o nível de dificuldade da atividade prática?,Qual o estágio de desenvolvimento do organismo observado?,Qual grupo biológico melhor descreve o organismo estudado?
0,5,10,3,60,moderado,intermediário,planta
1,6,10,3,120,difícil,avançado,planta
2,5,10,12,30,muito fácil,intermediário,planta
3,5,30,10,70,fácil,avançado,planta
4,5,20,5,10,difícil,avançado,planta
5,3,8,3,10,difícil,avançado,planta
6,5,10,30,10000,moderado,avançado,planta
7,5,10,5,50,moderado,avançado,planta
8,7,18,3,10,moderado,avançado,planta
9,5,4,3,10,moderado,avançado,bactéria
10,6,24,6,50,fácil,avançado,planta
11,6,20,3,210 x 297 mm,moderado,intermediário,planta
12,5,14,7,2025,muito fácil,avançado,bactéria
13,5,10,2,80,difícil,avançado,planta
14,6,20,3,5,moderado,intermediário,planta
15,6,30,70,150,fácil,avançado,planta
16,6,24,5,20,moderado,avançado,bactéria
17,2,10,3,150,difícil,intermediário,planta
18,2,8,4,230mm sulfite,moderado,intermediário,planta
19,6,30,1,50,muito difícil,intermediário,protista
20,5,10,12,300,moderado,intermediário,fungo
21,6,15,23,50,fácil,intermediário,planta
22,5,12,8,25,moderado,intermediário,planta

In [5]:
df.head(7)

,Quantos dias por semana você estuda Biologia?,Quantas horas você dedica aos estudos de Biologia em uma semana?,Quantas espécies de plantas você consegue identificar corretamente em uma atividade prática?,"Qual o tamanho da folha analisada, em milímetros?",Qual o nível de dificuldade da atividade prática?,Qual o estágio de desenvolvimento do organismo observado?,Qual grupo biológico melhor descreve o organismo estudado?
0,5,10,3,60,moderado,intermediário,planta
1,6,10,3,120,difícil,avançado,planta
2,5,10,12,30,muito fácil,intermediário,planta
3,5,30,10,70,fácil,avançado,planta
4,5,20,5,10,difícil,avançado,planta
5,3,8,3,10,difícil,avançado,planta
6,5,10,30,10000,moderado,avançado,planta

In [6]:
df.tail(7)

,Quantos dias por semana você estuda Biologia?,Quantas horas você dedica aos estudos de Biologia em uma semana?,Quantas espécies de plantas você consegue identificar corretamente em uma atividade prática?,"Qual o tamanho da folha analisada, em milímetros?",Qual o nível de dificuldade da atividade prática?,Qual o estágio de desenvolvimento do organismo observado?,Qual grupo biológico melhor descreve o organismo estudado?
16,6,24,5,20,moderado,avançado,bactéria
17,2,10,3,150,difícil,intermediário,planta
18,2,8,4,230mm sulfite,moderado,intermediário,planta
19,6,30,1,50,muito difícil,intermediário,protista
20,5,10,12,300,moderado,intermediário,fungo
21,6,15,23,50,fácil,intermediário,planta
22,5,12,8,25,moderado,intermediário,planta

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 7 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Quantos dias por semana você estuda Biologia?                                                 23 non-null     int64
 1   Quantas horas você dedica aos estudos de Biologia em uma semana?                              23 non-null     int64
 2   Quantas espécies de plantas você consegue identificar corretamente em uma atividade prática?  23 non-null     int64
 3   Qual o tamanho da folha analisada, em milímetros?                                             23 non-null     object
 4   Qual o nível de dificuldade da atividade prática?                                             23 non-null     object
 5   Qual o estágio de desenvolvimento do organismo observado?                                     23 non-null     object
 6   Qual grupo biológico melhor descreve o organismo estudado?                                    23 non-null     object
dtypes: int64(3), object(4)
memory usage: 1.4+ KB